- name: Terminate instances with playbook
  hosts: localhost
  connection: local
  tasks:
  - name: Terminate instances
    ec2:
     region: ap-south-1
     state: 'absent'
     instance_ids: "{{instance}}"
