
---
- hosts: localhost
  become: true
  vars_files:
    - myaws_key.yaml 
  tasks:
  - name: sg with inbound rule
    ec2_group:
      aws_access_key: "{{access_key}}"
      aws_secret_key: "{{secret_key}}"
      name: "{{ security_group_name }}"
      description: sg with new rules
      state: present
      vpc_id: "{{ vpc_id }}"
      region: ap-south-1
      rules:
        - proto: tcp
          from_port: 443
          to_port: 443
          cidr_ip: 0.0.0.0./0
        - proto: tcp
          from_port: 80
          to_port: 80
          cidr_ip: 0.0.0.0./0
