#Author: Nivedha B L 
#put: Security group name and vpc id 
#Description: 
#It takes security group name and vpc id to create/modify the inbound rule.
#if sg already exists, it modifies the rule, else it creates new sg and adds the given rule.

---
- hosts: localhost
  become: true
  tasks:
  - name: sg with inbound rule
    ec2_group:
      aws_access_key: AKIAYMHRXM6TTQQ4SVMA
      aws_secret_key: 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
      name: "{{ security_group_name }}"
      description: sg with new rules
      state: present
      vpc_id: "{{ vpc_id }}"
      region: ap-south-1
      rules:
        - proto: tcp
          from_port: 443
          to_port: 443
          cidr_ip: 0.0.0.0./0
        - proto: tcp
          from_port: 80
          to_port: 80
          cidr_ip: 0.0.0.0./0
